## TAREA 5

1. Cree dos archivos de tipo csv. En el primero debe colocar la información de 100 personas (clientes): id, cedula, nombre, apellido, número de cuenta.  En el segundo debe colocar transacciones de cada cliente. Por ejemplo (id= 3456, fecha = 29/01/2023, valor = -50_000). En total  mil transacciones.

2. Construya una función que lea el primer archivo y los suba a Pandas.
3. Construya una función  que haga lo mismo con el segundo archivo.
4.  Construya una función que reciba los dos objetos de Pandas y cree un diccionario, en donde hay solamente un registro por cada cliente. Por ejemplo ( esto es solamente un ejemplo)  {id= 2345, nombre='Luis Vazquez', cedula=20456912, transacciones=[ {fecha: 0/12/2021, valor: 45_000}, {fecha: 15/02/2023; valor: -70_000}, ...]}
5. Convierta el diccionario en un objeto json.
6. Guarde el objeto json como un archivo json.
7. Con base en todo lo anterior construya una clase, siguiendo las mejores prácticas que se verán en clase, que implemente toda la solución.

In [1]:
# Importación de librerias
import pandas as pd
import json as js

# Definición de la clase
class ImportClass:
    
    # Función inicial o constructor
    def __init__(self):
        # lectura de los archivos
            ## encoding='ISO-8859-1' es por los caracteres especiales que puede tener los datos
            ## sep=';' es para especificarle con que caracter queremos que nos reconozca la separación
        self.dateframe_clientes = pd.read_csv(r'Recursos/tarea_5_clientes.csv', encoding='ISO-8859-1', sep=';') 
        self.dateframe_movimientos = pd.read_csv(r'Recursos/tarea_5_movimientos.csv', encoding='ISO-8859-1', sep=';')
    
    # Función para crear un diccionario
    def createDictionary(self, dateframe_clientes = None, dateframe_movimientos = None):
        try:
             # Unir los dos objetos de Pandas en uno solo
                ## drop_duplicates(subset=['cliente_id']) es para eliminar los diferentes movimientos de un cliente en base a su id
            datos = pd.merge(dateframe_clientes, dateframe_movimientos.drop_duplicates(subset=['cliente_id']), on='cliente_id')

            # Crear un diccionario para almacenar la información de cada cliente
            diccionario = {}

            # Iterar sobre los registros en el objeto unido
            for _, registro in datos.iterrows():
                
                # Obtener el id del cliente y crear un registro si aún no existe
                cliente_id = registro['cliente_id']
                
                #Validación del id en el diccionario
                if cliente_id not in diccionario:
                    diccionario[cliente_id] = {
                        'cliente_id': cliente_id,
                        'cedula': registro['cedula'],
                        'nombre': registro['nombre'],
                        'apellido': registro['apellido'],
                        'numero_de_cuenta': registro['numero_de_cuenta'],
                        'transacciones': []
                    }

                # Agregar la información de la transacción al registro del cliente
                diccionario[cliente_id]['transacciones'].append({
                    'fecha': registro['fecha'],
                    'valor': registro['valor'],
                    'cliente_id': cliente_id
                })
            
            # Retorno de los valores en lista del diccionario
            return list(diccionario.values())
        except Exception as e: 
            print("Revisa el error => ", e) # Impresión del error personalizado

In [2]:
# Instancia del objeto
IC = ImportClass()

# Acceso a la lectura del archivo Iris.csv
IC.dateframe_clientes

    cliente_id      cedula          nombre   apellido numero_de_cuenta
0            1  1093847528         ANTONIO     GARCÍA      7,89633E+11
1            2   908382764          MANUEL   GONZÁLEZ      4,56987E+11
2            3   425860297            JOSE  RODRÍGUEZ      2,34568E+11
3            4   876549013       FRANCISCO  FERNÁNDEZ      8,47104E+11
4            5   253786940           DAVID      LÓPEZ       6,3246E+11
..         ...         ...             ...        ...              ...
95          96   438215967     LUIS MIGUEL      PARRA      4,56789E+11
96          97   725631489  JOSE FRANCISCO    ESTEBAN      8,90123E+11
97          98   162098357          XAVIER      BRAVO      2,34568E+11
98          99   856301274       JUAN LUIS   GALLARDO      6,78901E+11
99         100   243187560          ALBERT      ROJAS      1,23457E+11

[100 rows x 5 columns]

In [3]:
# Acceso a la lectura del archivo Iris.csv
IC.dateframe_movimientos

        id       fecha          valor  cliente_id
0     3456  19/10/2008   $ 1.946.738            1
1     3457  28/07/2013   $ 2.899.479            1
2     3458   2/09/2007   $ 1.664.000            1
3     3459   6/08/2017   $ 4.694.555            1
4     3460  15/01/2009     $ 583.598            1
...    ...         ...            ...         ...
1322  4778  16/11/2007   $ 2.934.819          100
1323  4779  18/11/2001   $ 1.206.979          100
1324  4780   2/04/2006     $ 356.539          100
1325  4781   8/07/2007   $ 4.804.983          100
1326  4782  27/08/2001     $ 156.261          100

[1327 rows x 4 columns]

In [4]:
# Variable para definición del Dataframe - Clientes
dfc = IC.dateframe_clientes

# Variable para definición del Dataframe - Movimientos
dfm = IC.dateframe_movimientos

# Llamado de la función para la creación de un diccionario
IC.createDictionary(dfc, dfm)

[{'cliente_id': 1,
  'cedula': 1093847528,
  'nombre': 'ANTONIO',
  'apellido': 'GARCÍA',
  'numero_de_cuenta': '7,89633E+11',
  'transacciones': [{'fecha': '19/10/2008',
    'valor': ' $ 1.946.738 ',
    'cliente_id': 1}]},
 {'cliente_id': 2,
  'cedula': 908382764,
  'nombre': 'MANUEL',
  'apellido': 'GONZÁLEZ',
  'numero_de_cuenta': '4,56987E+11',
  'transacciones': [{'fecha': '10/07/2022',
    'valor': ' $ 1.285.482 ',
    'cliente_id': 2}]},
 {'cliente_id': 3,
  'cedula': 425860297,
  'nombre': 'JOSE',
  'apellido': 'RODRÍGUEZ',
  'numero_de_cuenta': '2,34568E+11',
  'transacciones': [{'fecha': '1/10/2020',
    'valor': ' $ 3.862.856 ',
    'cliente_id': 3}]},
 {'cliente_id': 4,
  'cedula': 876549013,
  'nombre': 'FRANCISCO',
  'apellido': 'FERNÁNDEZ',
  'numero_de_cuenta': '8,47104E+11',
  'transacciones': [{'fecha': '8/09/2022',
    'valor': ' $ 409.362 ',
    'cliente_id': 4}]},
 {'cliente_id': 5,
  'cedula': 253786940,
  'nombre': 'DAVID',
  'apellido': 'LÓPEZ',
  'numero_de_cuenta': '6,3246E+11',
  'transacciones': [{'fecha': '13/06/2014',
    'valor': ' $ 2.632.851 ',
    'cliente_id': 5}]},
 {'cliente_id': 6,
  'cedula': 719462038,
  'nombre': 'JUAN',
  'apellido': 'MARTÍNEZ',
  'numero_de_cuenta': '2,15479E+11',
  'transacciones': [{'fecha': '12/01/2013',
    'valor': ' $ 1.108.239 ',
    'cliente_id': 6}]},
 {'cliente_id': 7,
  'cedula': 657302981,
  'nombre': 'JAVIER',
  'apellido': 'SÁNCHEZ',
  'numero_de_cuenta': '8,97641E+11',
  'transacciones': [{'fecha': '29/02/2016',
    'valor': ' $ 3.006.816 ',
    'cliente_id': 7}]},
 {'cliente_id': 8,
  'cedula': 281943065,
  'nombre': 'JOSE ANTONIO',
  'apellido': 'PÉREZ',
  'numero_de_cuenta': '3,65215E+11',
  'transacciones': [{'fecha': '12/12/2014',
    'valor': ' $ 1.988.560 ',
    'cliente_id': 8}]},
 {'cliente_id': 9,
  'cedula': 902568374,
  'nombre': 'DANIEL',
  'apellido': 'GÓMEZ',
  'numero_de_cuenta': '9,12346E+11',
  'transacciones': [{'fecha': '29/07/2015',
    'valor': ' $ 2.115.496 ',
    'cliente_id': 9}]},
 {'cliente_id': 10,
  'cedula': 432167895,
  'nombre': 'FRANCISCO JAVIER',
  'apellido': 'MARTIN',
  'numero_de_cuenta': '8,76543E+11',
  'transacciones': [{'fecha': '11/04/2004',
    'valor': ' $ 1.946.465 ',
    'cliente_id': 10}]},
 {'cliente_id': 11,
  'cedula': 605487239,
  'nombre': 'JOSE LUIS',
  'apellido': 'JIMÉNEZ',
  'numero_de_cuenta': '3,45679E+11',
  'transacciones': [{'fecha': '7/04/2015',
    'valor': ' $ 686.576 ',
    'cliente_id': 11}]},
 {'cliente_id': 12,
  'cedula': 873469521,
  'nombre': 'CARLOS',
  'apellido': 'RUIZ',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '22/03/2023',
    'valor': ' $ 1.431.963 ',
    'cliente_id': 12}]},
 {'cliente_id': 13,
  'cedula': 164279085,
  'nombre': 'JESUS',
  'apellido': 'HERNÁNDEZ',
  'numero_de_cuenta': '1,20988E+11',
  'transacciones': [{'fecha': '27/12/2005',
    'valor': ' $ 1.259.947 ',
    'cliente_id': 13}]},
 {'cliente_id': 14,
  'cedula': 935107246,
  'nombre': 'ALEJANDRO',
  'apellido': 'DIAZ',
  'numero_de_cuenta': '4,56789E+11',
  'transacciones': [{'fecha': '28/09/2018',
    'valor': ' $ 2.589.879 ',
    'cliente_id': 14}]},
 {'cliente_id': 15,
  'cedula': 750124869,
  'nombre': 'MIGUEL',
  'apellido': 'MORENO',
  'numero_de_cuenta': '9,01235E+11',
  'transacciones': [{'fecha': '22/11/2006',
    'valor': ' $ 178.819 ',
    'cliente_id': 15}]},
 {'cliente_id': 16,
  'cedula': 502936178,
  'nombre': 'JOSE MANUEL',
  'apellido': 'MUÑOZ',
  'numero_de_cuenta': '3,4121E+11',
  'transacciones': [{'fecha': '27/02/2018',
    'valor': ' $ 2.915.548 ',
    'cliente_id': 16}]},
 {'cliente_id': 17,
  'cedula': 319684057,
  'nombre': 'RAFAEL',
  'apellido': 'ÁLVAREZ',
  'numero_de_cuenta': '7,89456E+11',
  'transacciones': [{'fecha': '4/03/2004',
    'valor': ' $ 3.103.938 ',
    'cliente_id': 17}]},
 {'cliente_id': 18,
  'cedula': 871529306,
  'nombre': 'MIGUEL ANGEL',
  'apellido': 'ROMERO',
  'numero_de_cuenta': '5,68791E+11',
  'transacciones': [{'fecha': '19/06/2009',
    'valor': ' $ 752.938 ',
    'cliente_id': 18}]},
 {'cliente_id': 19,
  'cedula': 638290145,
  'nombre': 'PABLO',
  'apellido': 'ALONSO',
  'numero_de_cuenta': '7,86123E+11',
  'transacciones': [{'fecha': '1/02/2015',
    'valor': ' $ 2.251.171 ',
    'cliente_id': 19}]},
 {'cliente_id': 20,
  'cedula': 427510896,
  'nombre': 'PEDRO',
  'apellido': 'GUTIÉRREZ',
  'numero_de_cuenta': '2,10346E+11',
  'transacciones': [{'fecha': '5/05/2022',
    'valor': ' $ 4.220.694 ',
    'cliente_id': 20}]},
 {'cliente_id': 21,
  'cedula': 167893524,
  'nombre': 'ANGEL',
  'apellido': 'NAVARRO',
  'numero_de_cuenta': '9,07634E+11',
  'transacciones': [{'fecha': '6/09/2003',
    'valor': ' $ 1.347.164 ',
    'cliente_id': 21}]},
 {'cliente_id': 22,
  'cedula': 930684715,
  'nombre': 'SERGIO',
  'apellido': 'TORRES',
  'numero_de_cuenta': '1,20536E+11',
  'transacciones': [{'fecha': '9/10/2002',
    'valor': ' $ 4.664.330 ',
    'cliente_id': 22}]},
 {'cliente_id': 23,
  'cedula': 265197483,
  'nombre': 'JOSE MARIA',
  'apellido': 'DOMÍNGUEZ',
  'numero_de_cuenta': '5,60129E+11',
  'transacciones': [{'fecha': '2/05/2003',
    'valor': ' $ 1.074.684 ',
    'cliente_id': 23}]},
 {'cliente_id': 24,
  'cedula': 398652107,
  'nombre': 'FERNANDO',
  'apellido': 'VÁZQUEZ',
  'numero_de_cuenta': '1,03457E+11',
  'transacciones': [{'fecha': '16/06/2005',
    'valor': ' $ 3.456.718 ',
    'cliente_id': 24}]},
 {'cliente_id': 25,
  'cedula': 570298634,
  'nombre': 'JORGE',
  'apellido': 'RAMOS',
  'numero_de_cuenta': '7,8943E+11',
  'transacciones': [{'fecha': '28/10/2021',
    'valor': ' $ 4.096.602 ',
    'cliente_id': 25}]},
 {'cliente_id': 26,
  'cedula': 846219053,
  'nombre': 'LUIS',
  'apellido': 'GIL',
  'numero_de_cuenta': '3,45879E+11',
  'transacciones': [{'fecha': '8/04/2018',
    'valor': ' $ 4.008.268 ',
    'cliente_id': 26}]},
 {'cliente_id': 27,
  'cedula': 372648519,
  'nombre': 'ALBERTO',
  'apellido': 'RAMÍREZ',
  'numero_de_cuenta': '8,74568E+11',
  'transacciones': [{'fecha': '11/06/2019',
    'valor': ' $ 3.348.381 ',
    'cliente_id': 27}]},
 {'cliente_id': 28,
  'cedula': 941763028,
  'nombre': 'ALVARO',
  'apellido': 'SERRANO',
  'numero_de_cuenta': '5,67891E+11',
  'transacciones': [{'fecha': '26/12/2007',
    'valor': ' $ 4.100.632 ',
    'cliente_id': 28}]},
 {'cliente_id': 29,
  'cedula': 506389742,
  'nombre': 'JUAN CARLOS',
  'apellido': 'BLANCO',
  'numero_de_cuenta': '9,03569E+11',
  'transacciones': [{'fecha': '18/08/2005',
    'valor': ' $ 3.715.277 ',
    'cliente_id': 29}]},
 {'cliente_id': 30,
  'cedula': 765193284,
  'nombre': 'ADRIAN',
  'apellido': 'MOLINA',
  'numero_de_cuenta': '3,41206E+11',
  'transacciones': [{'fecha': '23/05/2003',
    'valor': ' $ 1.551.682 ',
    'cliente_id': 30}]},
 {'cliente_id': 31,
  'cedula': 429167538,
  'nombre': 'DIEGO',
  'apellido': 'MORALES',
  'numero_de_cuenta': '7,86354E+11',
  'transacciones': [{'fecha': '19/06/2022',
    'valor': ' $ 1.457.532 ',
    'cliente_id': 31}]},
 {'cliente_id': 32,
  'cedula': 817350296,
  'nombre': 'JUAN JOSE',
  'apellido': 'SUAREZ',
  'numero_de_cuenta': '1,20984E+11',
  'transacciones': [{'fecha': '5/08/2016',
    'valor': ' $ 1.801.500 ',
    'cliente_id': 32}]},
 {'cliente_id': 33,
  'cedula': 279436185,
  'nombre': 'RAUL',
  'apellido': 'ORTEGA',
  'numero_de_cuenta': '5,63402E+11',
  'transacciones': [{'fecha': '12/07/2018',
    'valor': ' $ 864.893 ',
    'cliente_id': 33}]},
 {'cliente_id': 34,
  'cedula': 603748219,
  'nombre': 'IVAN',
  'apellido': 'DELGADO',
  'numero_de_cuenta': '8,96342E+11',
  'transacciones': [{'fecha': '15/05/2001',
    'valor': ' $ 3.008.675 ',
    'cliente_id': 34}]},
 {'cliente_id': 35,
  'cedula': 958421073,
  'nombre': 'JUAN ANTONIO',
  'apellido': 'CASTRO',
  'numero_de_cuenta': '4,50128E+11',
  'transacciones': [{'fecha': '2/03/2021',
    'valor': ' $ 4.189.737 ',
    'cliente_id': 35}]},
 {'cliente_id': 36,
  'cedula': 295703816,
  'nombre': 'RUBEN',
  'apellido': 'ORTIZ',
  'numero_de_cuenta': '1,23457E+11',
  'transacciones': [{'fecha': '4/03/2004',
    'valor': ' $ 420.855 ',
    'cliente_id': 36}]},
 {'cliente_id': 37,
  'cedula': 748109352,
  'nombre': 'ENRIQUE',
  'apellido': 'RUBIO',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '28/04/2002',
    'valor': ' $ 4.487.533 ',
    'cliente_id': 37}]},
 {'cliente_id': 38,
  'cedula': 836491725,
  'nombre': 'OSCAR',
  'apellido': 'MARÍN',
  'numero_de_cuenta': '9,6354E+11',
  'transacciones': [{'fecha': '9/07/2022',
    'valor': ' $ 115.527 ',
    'cliente_id': 38}]},
 {'cliente_id': 39,
  'cedula': 124867530,
  'nombre': 'RAMON',
  'apellido': 'SANZ',
  'numero_de_cuenta': '1,20988E+11',
  'transacciones': [{'fecha': '21/06/2006',
    'valor': ' $ 841.456 ',
    'cliente_id': 39}]},
 {'cliente_id': 40,
  'cedula': 568937240,
  'nombre': 'ANDRES',
  'apellido': 'NÚÑEZ',
  'numero_de_cuenta': '3,45871E+11',
  'transacciones': [{'fecha': '17/10/2009',
    'valor': ' $ 2.689.862 ',
    'cliente_id': 40}]},
 {'cliente_id': 41,
  'cedula': 287356401,
  'nombre': 'JUAN MANUEL',
  'apellido': 'IGLESIAS',
  'numero_de_cuenta': '7,89635E+11',
  'transacciones': [{'fecha': '22/09/2004',
    'valor': ' $ 611.853 ',
    'cliente_id': 41}]},
 {'cliente_id': 42,
  'cedula': 750932468,
  'nombre': 'VICENTE',
  'apellido': 'MEDINA',
  'numero_de_cuenta': '9,87604E+11',
  'transacciones': [{'fecha': '4/02/2013',
    'valor': ' $ 2.134.896 ',
    'cliente_id': 42}]},
 {'cliente_id': 43,
  'cedula': 510893624,
  'nombre': 'SANTIAGO',
  'apellido': 'GARRIDO',
  'numero_de_cuenta': '4,57892E+11',
  'transacciones': [{'fecha': '27/06/2022',
    'valor': ' $ 3.594.096 ',
    'cliente_id': 43}]},
 {'cliente_id': 44,
  'cedula': 839205167,
  'nombre': 'JOAQUIN',
  'apellido': 'CORTES',
  'numero_de_cuenta': '9,01279E+11',
  'transacciones': [{'fecha': '29/12/2013',
    'valor': ' $ 932.844 ',
    'cliente_id': 44}]},
 {'cliente_id': 45,
  'cedula': 246801357,
  'nombre': 'MARIO',
  'apellido': 'CASTILLO',
  'numero_de_cuenta': '3,4561E+11',
  'transacciones': [{'fecha': '2/05/2006',
    'valor': ' $ 4.582.697 ',
    'cliente_id': 45}]},
 {'cliente_id': 46,
  'cedula': 640915283,
  'nombre': 'VICTOR',
  'apellido': 'SANTOS',
  'numero_de_cuenta': '6,78912E+11',
  'transacciones': [{'fecha': '14/06/2012',
    'valor': ' $ 3.378.523 ',
    'cliente_id': 46}]},
 {'cliente_id': 47,
  'cedula': 310725964,
  'nombre': 'EDUARDO',
  'apellido': 'LOZANO',
  'numero_de_cuenta': '1,29877E+11',
  'transacciones': [{'fecha': '11/10/2003',
    'valor': ' $ 1.295.147 ',
    'cliente_id': 47}]},
 {'cliente_id': 48,
  'cedula': 903457126,
  'nombre': 'ROBERTO',
  'apellido': 'GUERRERO',
  'numero_de_cuenta': '4,5789E+11',
  'transacciones': [{'fecha': '23/10/2022',
    'valor': ' $ 3.916.269 ',
    'cliente_id': 48}]},
 {'cliente_id': 49,
  'cedula': 508693274,
  'nombre': 'JAIME',
  'apellido': 'CANO',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '2/05/2018',
    'valor': ' $ 3.835.284 ',
    'cliente_id': 49}]},
 {'cliente_id': 50,
  'cedula': 961372048,
  'nombre': 'FRANCISCO JOSE',
  'apellido': 'PRIETO',
  'numero_de_cuenta': '5,67812E+11',
  'transacciones': [{'fecha': '18/08/2013',
    'valor': ' $ 3.992.390 ',
    'cliente_id': 50}]},
 {'cliente_id': 51,
  'cedula': 426581937,
  'nombre': 'MARCOS',
  'apellido': 'MÉNDEZ',
  'numero_de_cuenta': '9,01235E+11',
  'transacciones': [{'fecha': '19/12/2017',
    'valor': ' $ 4.097.275 ',
    'cliente_id': 51}]},
 {'cliente_id': 52,
  'cedula': 780162349,
  'nombre': 'HUGO',
  'apellido': 'CRUZ',
  'numero_de_cuenta': '6,78912E+11',
  'transacciones': [{'fecha': '29/03/2013',
    'valor': ' $ 3.115.522 ',
    'cliente_id': 52}]},
 {'cliente_id': 53,
  'cedula': 279846513,
  'nombre': 'IGNACIO',
  'apellido': 'CALVO',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '12/05/2009',
    'valor': ' $ 1.036.928 ',
    'cliente_id': 53}]},
 {'cliente_id': 54,
  'cedula': 604835219,
  'nombre': 'JORDI',
  'apellido': 'GALLEGO',
  'numero_de_cuenta': '1,23457E+11',
  'transacciones': [{'fecha': '29/04/2005',
    'valor': ' $ 271.135 ',
    'cliente_id': 54}]},
 {'cliente_id': 55,
  'cedula': 957310684,
  'nombre': 'ALFONSO',
  'apellido': 'VIDAL',
  'numero_de_cuenta': '5,67801E+11',
  'transacciones': [{'fecha': '8/04/2021',
    'valor': ' $ 230.553 ',
    'cliente_id': 55}]},
 {'cliente_id': 56,
  'cedula': 362958741,
  'nombre': 'RICARDO',
  'apellido': 'LEÓN',
  'numero_de_cuenta': '9,08765E+11',
  'transacciones': [{'fecha': '17/01/2007',
    'valor': ' $ 885.985 ',
    'cliente_id': 56}]},
 {'cliente_id': 57,
  'cedula': 894201536,
  'nombre': 'SALVADOR',
  'apellido': 'MÁRQUEZ',
  'numero_de_cuenta': '3,45679E+11',
  'transacciones': [{'fecha': '16/03/2007',
    'valor': ' $ 1.998.750 ',
    'cliente_id': 57}]},
 {'cliente_id': 58,
  'cedula': 142587093,
  'nombre': 'GUILLERMO',
  'apellido': 'HERRERA',
  'numero_de_cuenta': '6,78912E+11',
  'transacciones': [{'fecha': '15/03/2004',
    'valor': ' $ 3.315.972 ',
    'cliente_id': 58}]},
 {'cliente_id': 59,
  'cedula': 684019753,
  'nombre': 'MARC',
  'apellido': 'PEÑA',
  'numero_de_cuenta': '9,01235E+11',
  'transacciones': [{'fecha': '7/11/2018',
    'valor': ' $ 4.374.808 ',
    'cliente_id': 59}]},
 {'cliente_id': 60,
  'cedula': 518973246,
  'nombre': 'GABRIEL',
  'apellido': 'FLORES',
  'numero_de_cuenta': '3,45679E+11',
  'transacciones': [{'fecha': '29/05/2001',
    'valor': ' $ 3.674.472 ',
    'cliente_id': 60}]},
 {'cliente_id': 61,
  'cedula': 720534861,
  'nombre': 'MOHAMED',
  'apellido': 'CABRERA',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '4/05/2021',
    'valor': ' $ 3.415.863 ',
    'cliente_id': 61}]},
 {'cliente_id': 62,
  'cedula': 395016284,
  'nombre': 'EMILIO',
  'apellido': 'CAMPOS',
  'numero_de_cuenta': '5,67812E+11',
  'transacciones': [{'fecha': '16/09/2012',
    'valor': ' $ 1.435.161 ',
    'cliente_id': 62}]},
 {'cliente_id': 63,
  'cedula': 846173902,
  'nombre': 'GONZALO',
  'apellido': 'VEGA',
  'numero_de_cuenta': '9,01235E+11',
  'transacciones': [{'fecha': '22/01/2013',
    'valor': ' $ 4.541.297 ',
    'cliente_id': 63}]},
 {'cliente_id': 64,
  'cedula': 172930485,
  'nombre': 'MARTIN',
  'apellido': 'FUENTES',
  'numero_de_cuenta': '3,45679E+11',
  'transacciones': [{'fecha': '6/02/2019',
    'valor': ' $ 163.893 ',
    'cliente_id': 64}]},
 {'cliente_id': 65,
  'cedula': 683791254,
  'nombre': 'JOSE MIGUEL',
  'apellido': 'CARRASCO',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '21/08/2021',
    'valor': ' $ 699.496 ',
    'cliente_id': 65}]},
 {'cliente_id': 66,
  'cedula': 526348179,
  'nombre': 'JULIO',
  'apellido': 'DIEZ',
  'numero_de_cuenta': '5,67812E+11',
  'transacciones': [{'fecha': '5/06/2009',
    'valor': ' $ 3.155.984 ',
    'cliente_id': 66}]},
 {'cliente_id': 67,
  'cedula': 370925816,
  'nombre': 'JULIAN',
  'apellido': 'CABALLERO',
  'numero_de_cuenta': '9,01235E+11',
  'transacciones': [{'fecha': '3/06/2014',
    'valor': ' $ 4.059.436 ',
    'cliente_id': 67}]},
 {'cliente_id': 68,
  'cedula': 985124637,
  'nombre': 'TOMAS',
  'apellido': 'REYES',
  'numero_de_cuenta': '3,45679E+11',
  'transacciones': [{'fecha': '25/12/2002',
    'valor': ' $ 2.710.954 ',
    'cliente_id': 68}]},
 {'cliente_id': 69,
  'cedula': 260148973,
  'nombre': 'NICOLAS',
  'apellido': 'NIETO',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '28/08/2001',
    'valor': ' $ 2.638.851 ',
    'cliente_id': 69}]},
 {'cliente_id': 70,
  'cedula': 835619472,
  'nombre': 'AGUSTIN',
  'apellido': 'AGUILAR',
  'numero_de_cuenta': '5,67812E+11',
  'transacciones': [{'fecha': '3/12/2015',
    'valor': ' $ 1.753.634 ',
    'cliente_id': 70}]},
 {'cliente_id': 71,
  'cedula': 169840325,
  'nombre': 'JOSE RAMON',
  'apellido': 'PASCUAL',
  'numero_de_cuenta': '9,01235E+11',
  'transacciones': [{'fecha': '23/12/2017',
    'valor': ' $ 3.908.756 ',
    'cliente_id': 71}]},
 {'cliente_id': 72,
  'cedula': 742510863,
  'nombre': 'SAMUEL',
  'apellido': 'SANTANA',
  'numero_de_cuenta': '3,45679E+11',
  'transacciones': [{'fecha': '12/04/2016',
    'valor': ' $ 4.673.928 ',
    'cliente_id': 72}]},
 {'cliente_id': 73,
  'cedula': 395846271,
  'nombre': 'ISMAEL',
  'apellido': 'HERRERO',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '21/03/2008',
    'valor': ' $ 1.623.226 ',
    'cliente_id': 73}]},
 {'cliente_id': 74,
  'cedula': 810396425,
  'nombre': 'CRISTIAN',
  'apellido': 'LORENZO',
  'numero_de_cuenta': '5,67812E+11',
  'transacciones': [{'fecha': '20/01/2021',
    'valor': ' $ 683.888 ',
    'cliente_id': 74}]},
 {'cliente_id': 75,
  'cedula': 549763208,
  'nombre': 'LUCAS',
  'apellido': 'MONTERO',
  'numero_de_cuenta': '9,01235E+11',
  'transacciones': [{'fecha': '10/12/2003',
    'valor': ' $ 4.567.464 ',
    'cliente_id': 75}]},
 {'cliente_id': 76,
  'cedula': 312705684,
  'nombre': 'JOAN',
  'apellido': 'HIDALGO',
  'numero_de_cuenta': '3,45679E+11',
  'transacciones': [{'fecha': '20/07/2019',
    'valor': ' $ 3.510.272 ',
    'cliente_id': 76}]},
 {'cliente_id': 77,
  'cedula': 764820139,
  'nombre': 'FELIX',
  'apellido': 'GIMÉNEZ',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '28/01/2012',
    'valor': ' $ 514.653 ',
    'cliente_id': 77}]},
 {'cliente_id': 78,
  'cedula': 259034816,
  'nombre': 'AITOR',
  'apellido': 'IBÁÑEZ',
  'numero_de_cuenta': '5,67812E+11',
  'transacciones': [{'fecha': '2/09/2009',
    'valor': ' $ 558.915 ',
    'cliente_id': 78}]},
 {'cliente_id': 79,
  'cedula': 608974213,
  'nombre': 'HECTOR',
  'apellido': 'FERRER',
  'numero_de_cuenta': '9,01235E+11',
  'transacciones': [{'fecha': '23/08/2003',
    'valor': ' $ 1.736.414 ',
    'cliente_id': 79}]},
 {'cliente_id': 80,
  'cedula': 930145687,
  'nombre': 'IKER',
  'apellido': 'DURAN',
  'numero_de_cuenta': '3,45679E+11',
  'transacciones': [{'fecha': '16/03/2001',
    'valor': ' $ 1.259.352 ',
    'cliente_id': 80}]},
 {'cliente_id': 81,
  'cedula': 514763209,
  'nombre': 'ALEX',
  'apellido': 'SANTIAGO',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '29/06/2002',
    'valor': ' $ 1.188.894 ',
    'cliente_id': 81}]},
 {'cliente_id': 82,
  'cedula': 867395124,
  'nombre': 'JUAN FRANCISCO',
  'apellido': 'BENÍTEZ',
  'numero_de_cuenta': '5,67812E+11',
  'transacciones': [{'fecha': '22/05/2008',
    'valor': ' $ 4.835.201 ',
    'cliente_id': 82}]},
 {'cliente_id': 83,
  'cedula': 236790581,
  'nombre': 'JOSE CARLOS',
  'apellido': 'MORA',
  'numero_de_cuenta': '9,01235E+11',
  'transacciones': [{'fecha': '12/08/2019',
    'valor': ' $ 458.171 ',
    'cliente_id': 83}]},
 {'cliente_id': 84,
  'cedula': 978124506,
  'nombre': 'JOSEP',
  'apellido': 'VICENTE',
  'numero_de_cuenta': '3,45679E+11',
  'transacciones': [{'fecha': '22/12/2021',
    'valor': ' $ 529.011 ',
    'cliente_id': 84}]},
 {'cliente_id': 85,
  'cedula': 345728619,
  'nombre': 'SEBASTIAN',
  'apellido': 'VARGAS',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '14/07/2017',
    'valor': ' $ 1.974.896 ',
    'cliente_id': 85}]},
 {'cliente_id': 86,
  'cedula': 629415873,
  'nombre': 'CESAR',
  'apellido': 'ARIAS',
  'numero_de_cuenta': '5,67812E+11',
  'transacciones': [{'fecha': '16/06/2005',
    'valor': ' $ 1.667.305 ',
    'cliente_id': 86}]},
 {'cliente_id': 87,
  'cedula': 471025836,
  'nombre': 'MARIANO',
  'apellido': 'CARMONA',
  'numero_de_cuenta': '9,01235E+11',
  'transacciones': [{'fecha': '10/08/2001',
    'valor': ' $ 3.744.384 ',
    'cliente_id': 87}]},
 {'cliente_id': 88,
  'cedula': 813769245,
  'nombre': 'ALFREDO',
  'apellido': 'CRESPO',
  'numero_de_cuenta': '3,45679E+11',
  'transacciones': [{'fecha': '1/07/2012',
    'valor': ' $ 3.235.075 ',
    'cliente_id': 88}]},
 {'cliente_id': 89,
  'cedula': 568290137,
  'nombre': 'DOMINGO',
  'apellido': 'ROMÁN',
  'numero_de_cuenta': '7,89012E+11',
  'transacciones': [{'fecha': '19/11/2001',

In [5]:
# Asignación de la función a una variable para uso posterior
datos = IC.createDictionary(dfc, dfm)

In [6]:
# Convertimos el diccionario en un objeto JSON
json_datos = js.dumps(datos)

# Imprimimos el objeto JSON
json_datos

'[{"cliente_id": 1, "cedula": 1093847528, "nombre": "ANTONIO", "apellido": "GARC\\u00cdA", "numero_de_cuenta": "7,89633E+11", "transacciones": [{"fecha": "19/10/2008", "valor": " $ 1.946.738 ", "cliente_id": 1}]}, {"cliente_id": 2, "cedula": 908382764, "nombre": "MANUEL", "apellido": "GONZ\\u00c1LEZ", "numero_de_cuenta": "4,56987E+11", "transacciones": [{"fecha": "10/07/2022", "valor": " $ 1.285.482 ", "cliente_id": 2}]}, {"cliente_id": 3, "cedula": 425860297, "nombre": "JOSE", "apellido": "RODR\\u00cdGUEZ", "numero_de_cuenta": "2,34568E+11", "transacciones": [{"fecha": "1/10/2020", "valor": " $ 3.862.856 ", "cliente_id": 3}]}, {"cliente_id": 4, "cedula": 876549013, "nombre": "FRANCISCO", "apellido": "FERN\\u00c1NDEZ", "numero_de_cuenta": "8,47104E+11", "transacciones": [{"fecha": "8/09/2022", "valor": " $ 409.362 ", "cliente_id": 4}]}, {"cliente_id": 5, "cedula": 253786940, "nombre": "DAVID", "apellido": "L\\u00d3PEZ", "numero_de_cuenta": "6,3246E+11", "transacciones": [{"fecha": "13/06/2014", "valor": " $ 2.632.851 ", "cliente_id": 5}]}, {"cliente_id": 6, "cedula": 719462038, "nombre": "JUAN", "apellido": "MART\\u00cdNEZ", "numero_de_cuenta": "2,15479E+11", "transacciones": [{"fecha": "12/01/2013", "valor": " $ 1.108.239 ", "cliente_id": 6}]}, {"cliente_id": 7, "cedula": 657302981, "nombre": "JAVIER", "apellido": "S\\u00c1NCHEZ", "numero_de_cuenta": "8,97641E+11", "transacciones": [{"fecha": "29/02/2016", "valor": " $ 3.006.816 ", "cliente_id": 7}]}, {"cliente_id": 8, "cedula": 281943065, "nombre": "JOSE ANTONIO", "apellido": "P\\u00c9REZ", "numero_de_cuenta": "3,65215E+11", "transacciones": [{"fecha": "12/12/2014", "valor": " $ 1.988.560 ", "cliente_id": 8}]}, {"cliente_id": 9, "cedula": 902568374, "nombre": "DANIEL", "apellido": "G\\u00d3MEZ", "numero_de_cuenta": "9,12346E+11", "transacciones": [{"fecha": "29/07/2015", "valor": " $ 2.115.496 ", "cliente_id": 9}]}, {"cliente_id": 10, "cedula": 432167895, "nombre": "FRANCISCO JAVIER", "apellido": "MARTIN", "numero_de_cuenta": "8,76543E+11", "transacciones": [{"fecha": "11/04/2004", "valor": " $ 1.946.465 ", "cliente_id": 10}]}, {"cliente_id": 11, "cedula": 605487239, "nombre": "JOSE LUIS", "apellido": "JIM\\u00c9NEZ", "numero_de_cuenta": "3,45679E+11", "transacciones": [{"fecha": "7/04/2015", "valor": " $ 686.576 ", "cliente_id": 11}]}, {"cliente_id": 12, "cedula": 873469521, "nombre": "CARLOS", "apellido": "RUIZ", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "22/03/2023", "valor": " $ 1.431.963 ", "cliente_id": 12}]}, {"cliente_id": 13, "cedula": 164279085, "nombre": "JESUS", "apellido": "HERN\\u00c1NDEZ", "numero_de_cuenta": "1,20988E+11", "transacciones": [{"fecha": "27/12/2005", "valor": " $ 1.259.947 ", "cliente_id": 13}]}, {"cliente_id": 14, "cedula": 935107246, "nombre": "ALEJANDRO", "apellido": "DIAZ", "numero_de_cuenta": "4,56789E+11", "transacciones": [{"fecha": "28/09/2018", "valor": " $ 2.589.879 ", "cliente_id": 14}]}, {"cliente_id": 15, "cedula": 750124869, "nombre": "MIGUEL", "apellido": "MORENO", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "22/11/2006", "valor": " $ 178.819 ", "cliente_id": 15}]}, {"cliente_id": 16, "cedula": 502936178, "nombre": "JOSE MANUEL", "apellido": "MU\\u00d1OZ", "numero_de_cuenta": "3,4121E+11", "transacciones": [{"fecha": "27/02/2018", "valor": " $ 2.915.548 ", "cliente_id": 16}]}, {"cliente_id": 17, "cedula": 319684057, "nombre": "RAFAEL", "apellido": "\\u00c1LVAREZ", "numero_de_cuenta": "7,89456E+11", "transacciones": [{"fecha": "4/03/2004", "valor": " $ 3.103.938 ", "cliente_id": 17}]}, {"cliente_id": 18, "cedula": 871529306, "nombre": "MIGUEL ANGEL", "apellido": "ROMERO", "numero_de_cuenta": "5,68791E+11", "transacciones": [{"fecha": "19/06/2009", "valor": " $ 752.938 ", "cliente_id": 18}]}, {"cliente_id": 19, "cedula": 638290145, "nombre": "PABLO", "apellido": "ALONSO", "numero_de_cuenta": "7,86123E+11", "transacciones": [{"fecha": "1/02/2015", "valor": " $ 2.251.171 ", "cliente_id": 19}]}, {"cliente_id": 20, "cedula": 427510896, "nombre": "PEDRO", "apellido": "GUTI\\u00c9RREZ", "numero_de_cuenta": "2,10346E+11", "transacciones": [{"fecha": "5/05/2022", "valor": " $ 4.220.694 ", "cliente_id": 20}]}, {"cliente_id": 21, "cedula": 167893524, "nombre": "ANGEL", "apellido": "NAVARRO", "numero_de_cuenta": "9,07634E+11", "transacciones": [{"fecha": "6/09/2003", "valor": " $ 1.347.164 ", "cliente_id": 21}]}, {"cliente_id": 22, "cedula": 930684715, "nombre": "SERGIO", "apellido": "TORRES", "numero_de_cuenta": "1,20536E+11", "transacciones": [{"fecha": "9/10/2002", "valor": " $ 4.664.330 ", "cliente_id": 22}]}, {"cliente_id": 23, "cedula": 265197483, "nombre": "JOSE MARIA", "apellido": "DOM\\u00cdNGUEZ", "numero_de_cuenta": "5,60129E+11", "transacciones": [{"fecha": "2/05/2003", "valor": " $ 1.074.684 ", "cliente_id": 23}]}, {"cliente_id": 24, "cedula": 398652107, "nombre": "FERNANDO", "apellido": "V\\u00c1ZQUEZ", "numero_de_cuenta": "1,03457E+11", "transacciones": [{"fecha": "16/06/2005", "valor": " $ 3.456.718 ", "cliente_id": 24}]}, {"cliente_id": 25, "cedula": 570298634, "nombre": "JORGE", "apellido": "RAMOS", "numero_de_cuenta": "7,8943E+11", "transacciones": [{"fecha": "28/10/2021", "valor": " $ 4.096.602 ", "cliente_id": 25}]}, {"cliente_id": 26, "cedula": 846219053, "nombre": "LUIS", "apellido": "GIL", "numero_de_cuenta": "3,45879E+11", "transacciones": [{"fecha": "8/04/2018", "valor": " $ 4.008.268 ", "cliente_id": 26}]}, {"cliente_id": 27, "cedula": 372648519, "nombre": "ALBERTO", "apellido": "RAM\\u00cdREZ", "numero_de_cuenta": "8,74568E+11", "transacciones": [{"fecha": "11/06/2019", "valor": " $ 3.348.381 ", "cliente_id": 27}]}, {"cliente_id": 28, "cedula": 941763028, "nombre": "ALVARO", "apellido": "SERRANO", "numero_de_cuenta": "5,67891E+11", "transacciones": [{"fecha": "26/12/2007", "valor": " $ 4.100.632 ", "cliente_id": 28}]}, {"cliente_id": 29, "cedula": 506389742, "nombre": "JUAN CARLOS", "apellido": "BLANCO", "numero_de_cuenta": "9,03569E+11", "transacciones": [{"fecha": "18/08/2005", "valor": " $ 3.715.277 ", "cliente_id": 29}]}, {"cliente_id": 30, "cedula": 765193284, "nombre": "ADRIAN", "apellido": "MOLINA", "numero_de_cuenta": "3,41206E+11", "transacciones": [{"fecha": "23/05/2003", "valor": " $ 1.551.682 ", "cliente_id": 30}]}, {"cliente_id": 31, "cedula": 429167538, "nombre": "DIEGO", "apellido": "MORALES", "numero_de_cuenta": "7,86354E+11", "transacciones": [{"fecha": "19/06/2022", "valor": " $ 1.457.532 ", "cliente_id": 31}]}, {"cliente_id": 32, "cedula": 817350296, "nombre": "JUAN JOSE", "apellido": "SUAREZ", "numero_de_cuenta": "1,20984E+11", "transacciones": [{"fecha": "5/08/2016", "valor": " $ 1.801.500 ", "cliente_id": 32}]}, {"cliente_id": 33, "cedula": 279436185, "nombre": "RAUL", "apellido": "ORTEGA", "numero_de_cuenta": "5,63402E+11", "transacciones": [{"fecha": "12/07/2018", "valor": " $ 864.893 ", "cliente_id": 33}]}, {"cliente_id": 34, "cedula": 603748219, "nombre": "IVAN", "apellido": "DELGADO", "numero_de_cuenta": "8,96342E+11", "transacciones": [{"fecha": "15/05/2001", "valor": " $ 3.008.675 ", "cliente_id": 34}]}, {"cliente_id": 35, "cedula": 958421073, "nombre": "JUAN ANTONIO", "apellido": "CASTRO", "numero_de_cuenta": "4,50128E+11", "transacciones": [{"fecha": "2/03/2021", "valor": " $ 4.189.737 ", "cliente_id": 35}]}, {"cliente_id": 36, "cedula": 295703816, "nombre": "RUBEN", "apellido": "ORTIZ", "numero_de_cuenta": "1,23457E+11", "transacciones": [{"fecha": "4/03/2004", "valor": " $ 420.855 ", "cliente_id": 36}]}, {"cliente_id": 37, "cedula": 748109352, "nombre": "ENRIQUE", "apellido": "RUBIO", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "28/04/2002", "valor": " $ 4.487.533 ", "cliente_id": 37}]}, {"cliente_id": 38, "cedula": 836491725, "nombre": "OSCAR", "apellido": "MAR\\u00cdN", "numero_de_cuenta": "9,6354E+11", "transacciones": [{"fecha": "9/07/2022", "valor": " $ 115.527 ", "cliente_id": 38}]}, {"cliente_id": 39, "cedula": 124867530, "nombre": "RAMON", "apellido": "SANZ", "numero_de_cuenta": "1,20988E+11", "transacciones": [{"fecha": "21/06/2006", "valor": " $ 841.456 ", "cliente_id": 39}]}, {"cliente_id": 40, "cedula": 568937240, "nombre": "ANDRES", "apellido": "N\\u00da\\u00d1EZ", "numero_de_cuenta": "3,45871E+11", "transacciones": [{"fecha": "17/10/2009", "valor": " $ 2.689.862 ", "cliente_id": 40}]}, {"cliente_id": 41, "cedula": 287356401, "nombre": "JUAN MANUEL", "apellido": "IGLESIAS", "numero_de_cuenta": "7,89635E+11", "transacciones": [{"fecha": "22/09/2004", "valor": " $ 611.853 ", "cliente_id": 41}]}, {"cliente_id": 42, "cedula": 750932468, "nombre": "VICENTE", "apellido": "MEDINA", "numero_de_cuenta": "9,87604E+11", "transacciones": [{"fecha": "4/02/2013", "valor": " $ 2.134.896 ", "cliente_id": 42}]}, {"cliente_id": 43, "cedula": 510893624, "nombre": "SANTIAGO", "apellido": "GARRIDO", "numero_de_cuenta": "4,57892E+11", "transacciones": [{"fecha": "27/06/2022", "valor": " $ 3.594.096 ", "cliente_id": 43}]}, {"cliente_id": 44, "cedula": 839205167, "nombre": "JOAQUIN", "apellido": "CORTES", "numero_de_cuenta": "9,01279E+11", "transacciones": [{"fecha": "29/12/2013", "valor": " $ 932.844 ", "cliente_id": 44}]}, {"cliente_id": 45, "cedula": 246801357, "nombre": "MARIO", "apellido": "CASTILLO", "numero_de_cuenta": "3,4561E+11", "transacciones": [{"fecha": "2/05/2006", "valor": " $ 4.582.697 ", "cliente_id": 45}]}, {"cliente_id": 46, "cedula": 640915283, "nombre": "VICTOR", "apellido": "SANTOS", "numero_de_cuenta": "6,78912E+11", "transacciones": [{"fecha": "14/06/2012", "valor": " $ 3.378.523 ", "cliente_id": 46}]}, {"cliente_id": 47, "cedula": 310725964, "nombre": "EDUARDO", "apellido": "LOZANO", "numero_de_cuenta": "1,29877E+11", "transacciones": [{"fecha": "11/10/2003", "valor": " $ 1.295.147 ", "cliente_id": 47}]}, {"cliente_id": 48, "cedula": 903457126, "nombre": "ROBERTO", "apellido": "GUERRERO", "numero_de_cuenta": "4,5789E+11", "transacciones": [{"fecha": "23/10/2022", "valor": " $ 3.916.269 ", "cliente_id": 48}]}, {"cliente_id": 49, "cedula": 508693274, "nombre": "JAIME", "apellido": "CANO", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "2/05/2018", "valor": " $ 3.835.284 ", "cliente_id": 49}]}, {"cliente_id": 50, "cedula": 961372048, "nombre": "FRANCISCO JOSE", "apellido": "PRIETO", "numero_de_cuenta": "5,67812E+11", "transacciones": [{"fecha": "18/08/2013", "valor": " $ 3.992.390 ", "cliente_id": 50}]}, {"cliente_id": 51, "cedula": 426581937, "nombre": "MARCOS", "apellido": "M\\u00c9NDEZ", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "19/12/2017", "valor": " $ 4.097.275 ", "cliente_id": 51}]}, {"cliente_id": 52, "cedula": 780162349, "nombre": "HUGO", "apellido": "CRUZ", "numero_de_cuenta": "6,78912E+11", "transacciones": [{"fecha": "29/03/2013", "valor": " $ 3.115.522 ", "cliente_id": 52}]}, {"cliente_id": 53, "cedula": 279846513, "nombre": "IGNACIO", "apellido": "CALVO", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "12/05/2009", "valor": " $ 1.036.928 ", "cliente_id": 53}]}, {"cliente_id": 54, "cedula": 604835219, "nombre": "JORDI", "apellido": "GALLEGO", "numero_de_cuenta": "1,23457E+11", "transacciones": [{"fecha": "29/04/2005", "valor": " $ 271.135 ", "cliente_id": 54}]}, {"cliente_id": 55, "cedula": 957310684, "nombre": "ALFONSO", "apellido": "VIDAL", "numero_de_cuenta": "5,67801E+11", "transacciones": [{"fecha": "8/04/2021", "valor": " $ 230.553 ", "cliente_id": 55}]}, {"cliente_id": 56, "cedula": 362958741, "nombre": "RICARDO", "apellido": "LE\\u00d3N", "numero_de_cuenta": "9,08765E+11", "transacciones": [{"fecha": "17/01/2007", "valor": " $ 885.985 ", "cliente_id": 56}]}, {"cliente_id": 57, "cedula": 894201536, "nombre": "SALVADOR", "apellido": "M\\u00c1RQUEZ", "numero_de_cuenta": "3,45679E+11", "transacciones": [{"fecha": "16/03/2007", "valor": " $ 1.998.750 ", "cliente_id": 57}]}, {"cliente_id": 58, "cedula": 142587093, "nombre": "GUILLERMO", "apellido": "HERRERA", "numero_de_cuenta": "6,78912E+11", "transacciones": [{"fecha": "15/03/2004", "valor": " $ 3.315.972 ", "cliente_id": 58}]}, {"cliente_id": 59, "cedula": 684019753, "nombre": "MARC", "apellido": "PE\\u00d1A", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "7/11/2018", "valor": " $ 4.374.808 ", "cliente_id": 59}]}, {"cliente_id": 60, "cedula": 518973246, "nombre": "GABRIEL", "apellido": "FLORES", "numero_de_cuenta": "3,45679E+11", "transacciones": [{"fecha": "29/05/2001", "valor": " $ 3.674.472 ", "cliente_id": 60}]}, {"cliente_id": 61, "cedula": 720534861, "nombre": "MOHAMED", "apellido": "CABRERA", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "4/05/2021", "valor": " $ 3.415.863 ", "cliente_id": 61}]}, {"cliente_id": 62, "cedula": 395016284, "nombre": "EMILIO", "apellido": "CAMPOS", "numero_de_cuenta": "5,67812E+11", "transacciones": [{"fecha": "16/09/2012", "valor": " $ 1.435.161 ", "cliente_id": 62}]}, {"cliente_id": 63, "cedula": 846173902, "nombre": "GONZALO", "apellido": "VEGA", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "22/01/2013", "valor": " $ 4.541.297 ", "cliente_id": 63}]}, {"cliente_id": 64, "cedula": 172930485, "nombre": "MARTIN", "apellido": "FUENTES", "numero_de_cuenta": "3,45679E+11", "transacciones": [{"fecha": "6/02/2019", "valor": " $ 163.893 ", "cliente_id": 64}]}, {"cliente_id": 65, "cedula": 683791254, "nombre": "JOSE MIGUEL", "apellido": "CARRASCO", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "21/08/2021", "valor": " $ 699.496 ", "cliente_id": 65}]}, {"cliente_id": 66, "cedula": 526348179, "nombre": "JULIO", "apellido": "DIEZ", "numero_de_cuenta": "5,67812E+11", "transacciones": [{"fecha": "5/06/2009", "valor": " $ 3.155.984 ", "cliente_id": 66}]}, {"cliente_id": 67, "cedula": 370925816, "nombre": "JULIAN", "apellido": "CABALLERO", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "3/06/2014", "valor": " $ 4.059.436 ", "cliente_id": 67}]}, {"cliente_id": 68, "cedula": 985124637, "nombre": "TOMAS", "apellido": "REYES", "numero_de_cuenta": "3,45679E+11", "transacciones": [{"fecha": "25/12/2002", "valor": " $ 2.710.954 ", "cliente_id": 68}]}, {"cliente_id": 69, "cedula": 260148973, "nombre": "NICOLAS", "apellido": "NIETO", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "28/08/2001", "valor": " $ 2.638.851 ", "cliente_id": 69}]}, {"cliente_id": 70, "cedula": 835619472, "nombre": "AGUSTIN", "apellido": "AGUILAR", "numero_de_cuenta": "5,67812E+11", "transacciones": [{"fecha": "3/12/2015", "valor": " $ 1.753.634 ", "cliente_id": 70}]}, {"cliente_id": 71, "cedula": 169840325, "nombre": "JOSE RAMON", "apellido": "PASCUAL", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "23/12/2017", "valor": " $ 3.908.756 ", "cliente_id": 71}]}, {"cliente_id": 72, "cedula": 742510863, "nombre": "SAMUEL", "apellido": "SANTANA", "numero_de_cuenta": "3,45679E+11", "transacciones": [{"fecha": "12/04/2016", "valor": " $ 4.673.928 ", "cliente_id": 72}]}, {"cliente_id": 73, "cedula": 395846271, "nombre": "ISMAEL", "apellido": "HERRERO", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "21/03/2008", "valor": " $ 1.623.226 ", "cliente_id": 73}]}, {"cliente_id": 74, "cedula": 810396425, "nombre": "CRISTIAN", "apellido": "LORENZO", "numero_de_cuenta": "5,67812E+11", "transacciones": [{"fecha": "20/01/2021", "valor": " $ 683.888 ", "cliente_id": 74}]}, {"cliente_id": 75, "cedula": 549763208, "nombre": "LUCAS", "apellido": "MONTERO", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "10/12/2003", "valor": " $ 4.567.464 ", "cliente_id": 75}]}, {"cliente_id": 76, "cedula": 312705684, "nombre": "JOAN", "apellido": "HIDALGO", "numero_de_cuenta": "3,45679E+11", "transacciones": [{"fecha": "20/07/2019", "valor": " $ 3.510.272 ", "cliente_id": 76}]}, {"cliente_id": 77, "cedula": 764820139, "nombre": "FELIX", "apellido": "GIM\\u00c9NEZ", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "28/01/2012", "valor": " $ 514.653 ", "cliente_id": 77}]}, {"cliente_id": 78, "cedula": 259034816, "nombre": "AITOR", "apellido": "IB\\u00c1\\u00d1EZ", "numero_de_cuenta": "5,67812E+11", "transacciones": [{"fecha": "2/09/2009", "valor": " $ 558.915 ", "cliente_id": 78}]}, {"cliente_id": 79, "cedula": 608974213, "nombre": "HECTOR", "apellido": "FERRER", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "23/08/2003", "valor": " $ 1.736.414 ", "cliente_id": 79}]}, {"cliente_id": 80, "cedula": 930145687, "nombre": "IKER", "apellido": "DURAN", "numero_de_cuenta": "3,45679E+11", "transacciones": [{"fecha": "16/03/2001", "valor": " $ 1.259.352 ", "cliente_id": 80}]}, {"cliente_id": 81, "cedula": 514763209, "nombre": "ALEX", "apellido": "SANTIAGO", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "29/06/2002", "valor": " $ 1.188.894 ", "cliente_id": 81}]}, {"cliente_id": 82, "cedula": 867395124, "nombre": "JUAN FRANCISCO", "apellido": "BEN\\u00cdTEZ", "numero_de_cuenta": "5,67812E+11", "transacciones": [{"fecha": "22/05/2008", "valor": " $ 4.835.201 ", "cliente_id": 82}]}, {"cliente_id": 83, "cedula": 236790581, "nombre": "JOSE CARLOS", "apellido": "MORA", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "12/08/2019", "valor": " $ 458.171 ", "cliente_id": 83}]}, {"cliente_id": 84, "cedula": 978124506, "nombre": "JOSEP", "apellido": "VICENTE", "numero_de_cuenta": "3,45679E+11", "transacciones": [{"fecha": "22/12/2021", "valor": " $ 529.011 ", "cliente_id": 84}]}, {"cliente_id": 85, "cedula": 345728619, "nombre": "SEBASTIAN", "apellido": "VARGAS", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "14/07/2017", "valor": " $ 1.974.896 ", "cliente_id": 85}]}, {"cliente_id": 86, "cedula": 629415873, "nombre": "CESAR", "apellido": "ARIAS", "numero_de_cuenta": "5,67812E+11", "transacciones": [{"fecha": "16/06/2005", "valor": " $ 1.667.305 ", "cliente_id": 86}]}, {"cliente_id": 87, "cedula": 471025836, "nombre": "MARIANO", "apellido": "CARMONA", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "10/08/2001", "valor": " $ 3.744.384 ", "cliente_id": 87}]}, {"cliente_id": 88, "cedula": 813769245, "nombre": "ALFREDO", "apellido": "CRESPO", "numero_de_cuenta": "3,45679E+11", "transacciones": [{"fecha": "1/07/2012", "valor": " $ 3.235.075 ", "cliente_id": 88}]}, {"cliente_id": 89, "cedula": 568290137, "nombre": "DOMINGO", "apellido": "ROM\\u00c1N", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "19/11/2001", "valor": " $ 434.812 ", "cliente_id": 89}]}, {"cliente_id": 90, "cedula": 305874619, "nombre": "MATEO", "apellido": "PASTOR", "numero_de_cuenta": "5,67812E+11", "transacciones": [{"fecha": "22/11/2010", "valor": " $ 3.655.951 ", "cliente_id": 90}]}, {"cliente_id": 91, "cedula": 749036218, "nombre": "JOSE ANGEL", "apellido": "SOTO", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "28/11/2010", "valor": " $ 3.140.335 ", "cliente_id": 91}]}, {"cliente_id": 92, "cedula": 214697583, "nombre": "RODRIGO", "apellido": "S\\u00c1EZ", "numero_de_cuenta": "3,45679E+11", "transacciones": [{"fecha": "1/02/2004", "valor": " $ 3.837.420 ", "cliente_id": 92}]}, {"cliente_id": 93, "cedula": 986107324, "nombre": "VICTOR MANUEL", "apellido": "VELASCO", "numero_de_cuenta": "7,89012E+11", "transacciones": [{"fecha": "31/07/2016", "valor": " $ 2.042.839 ", "cliente_id": 93}]}, {"cliente_id": 94, "cedula": 543216978, "nombre": "FELIPE", "apellido": "MOYA", "numero_de_cuenta": "6,78901E+11", "transacciones": [{"fecha": "31/08/2007", "valor": " $ 344.066 ", "cliente_id": 94}]}, {"cliente_id": 95, "cedula": 901865732, "nombre": "JOSE IGNACIO", "apellido": "SOLER", "numero_de_cuenta": "9,01235E+11", "transacciones": [{"fecha": "14/02/2006", "valor": " $ 2.049.521 ", "cliente_id": 95}]}, {"cliente_id": 96, "cedula": 438215967, "nombre": "LUIS MIGUEL", "apellido": "PARRA", "numero_de_cuenta": "4,56789E+11", "transacciones": [{"fecha": "1/05/2023", "valor": " $ 4.714.499 ", "cliente_id": 96}]}, {"cliente_id": 97, "ce

In [7]:
# Guardamos el objeto JSON en un archivo
    ## la "w" es el parametro para written (escritura)
with open(r'Recursos/datos.json', 'w') as archivo:
    js.dump(json_datos, archivo)